gridscale/gscloud

README.md, cmd/cliconfig.go, cmd/client.go, cmd/kubernetes.go, cmd/root.go
gscloud save-kubeconfig the account should be taken from stored viper cliconfig
=> Fix gscloud save-kubeconfig

README.md, cmd/kubernetes.go
Make kubernetes sub-command help texts a little bit shorter.
=> Update k8s help texts

.gitignore, cmd/cliconfig.go, go.mod, go.sum
Fix for this issue: https://github.com/gridscale/gscloud/issues/5
=> gscloud lookup real absolute executable file path

cmd/cliconfig.go, cmd/kubernetes.go, cmd/makeConfig.go, cmd/root.go
solving issue: https://github.com/gridscale/gscloud/issues/8
=> Use the standard Cache location to store gscloud cache

Makefile, cmd/kubernetes.go, cmd/version.go, go.mod, main.go, vendor/vendor.json
gscloud version
v0.2.0-beta
https://github.com/gridscale/gscloud/issues/14
https://gridscale.atlassian.net/browse/GD-2675
=> Add version subcommand

.travis.yml, README.md
- .travis.yml
- README.md
___
Added a travis file and inserted a badge in the README,
to see if it runs the tests and builds or not.
Resolves: GD-2673, DX-709
=> Implementation of a simple pipeline for Travis - CI

cmd/network.go, cmd/root.go, cmd/server.go, cmd/storage.go
```
$ ./gscloud network
NAME             LOCATION  CREATETIME  STATUS  
Public Network   de/fra0   1970-01-01  active  
Updated network  de/fra0   1970-01-01  active  
$ ./gscloud network --id
NAME             LOCATION  CREATETIME  STATUS  UUID                                  
Public Network   de/fra0   1970-01-01  active  xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx  
Updated network  de/fra0   1970-01-01  active  xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 
```
=> New functionality --id flag

cmd/network.go, cmd/root.go, cmd/server.go, cmd/storage.go
- Removed unnecessary redundancy.
- Refactor code and made heading a variable
- Proofs for --id before prints an extra row
=> Remove redundancy, optimized

cmd/network.go, cmd/server.go, cmd/storage.go
```
$ ./gscloud server --on xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx     
$ ./gscloud server --off xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx   
```
See: https://github.com/gridscale/gscloud/issues/31
=> Turn server on/off by uuid

render/render_test.go
=> add AsJSON's unit test

cmd/network.go, cmd/root.go, cmd/server.go, cmd/sshKey.go, cmd/storage.go
-  Remove --id -i flag
-  Add ID column print by default
Fixes https://github.com/gridscale/gscloud/issues/42
=> No --id flag anymore, ID column is now 1st column

cmd/server.go
- Add createOptions struct
- Embed mutex
- Remove return 0 in Error
- Remove unnecessary alias
- Remove arbitrary label
- Customize flags to match new struct
- Remove default flag values
Fixes GD-2686
without template
`$ ./gscloud server create --name "just server" --cpu 2  --mem 4`
with template
`$ ./gscloud server create --name "Debian Server" --cpu 2  --mem 4 --with-template "Debian 9" --storage-size 10 -p "Passw0rd" -H "deblinux"`
=> Add Create Server Function 

CHANGELOG.md, cmd/template.go, runtime/runtime.go
Adds `gscloud template ls`.
Fixes https://github.com/gridscale/gscloud/issues/59.
=> Add template ls

cmd/kubernetes.go
Do not swallow errors in f`etchKubeConfigFromProvider` but pass them down
to caller. Also write original errors to stderr.
Furthermore use log.Fatal library to print errors to stderr and exit the
process with non-zero status code where appropriate.
Fixes https://github.com/gridscale/gscloud/issues/18
=> kubernetes command: improve error handling

LICENSE
as this "single-commit" PR suggests, it aims to update the year on the **LICENSE** file; nothing more.
=> LICENSE: year update

README.md
suggestions to be applied into **README.md**
- shell completion is not defined in this repo, so take that information out;
- indent and sort the example to generate shell completions for `bash` and `zsh`;
- make "_Kubernetes_" a section, not a sentence;
- update the _Overview_ about the tool;
- keep the "usage" help message, but in a way we show only the help message.
=> README update and suggestions

.githooks/pre-push/check-changelog.sh
- verify if the **CHANGELOG.md** exists;
- make sure we tagged a release before pushing;
- the changelog file must contain a date;
- date format defined by https://pkidd.com/date.htm
=>  git HOOK: add first 'pre-push' hook to check CHANGELOG

cmd/server.go
password is given on storage create success
=> fixes #104

cmd/network.go
closes #106 
we still need to implement l2 security at some point, this just allows network creation /w name
=> add network creation to gscloud

cmd/postgresql.go
Implements issue #122 as `gscloud postgresql releases`.
=> Add gscloud-postgresql-releases command

cmd/isoImage.go
=> fix iso-image ls --quiet to show only image-ids

cmd/kubernetes.go, cmd/postgresql.go, cmd/root.go, cmd/root_test.go, runtime/runtime.go, utils/utils.go, utils/utils_test.go
Seperates some util functions from their current packages and puts them in `utils` package
=> Seperate utils

cmd/root.go
Use --config file flag when it's specified
Fixes #156
=> Fix --config flag (#156)

homebrew/gscloud.rb
This is a homebrew formula for gscloud (see #127)
=> Add homebrew formula for v0.12.0
