gridscale/gscloud

- cmd/kubernetes.go
- go.mod
- main.go
- vendor/vendor.json
Just figured that this is still from public GitLab instance. This PR changes the module path from gitlab.com/gridscale/gscloud → to github.com.
> Change module path to github.com/gridscale/gscloud

- cmd/version.go
gscloud version displays latest Git commit SHA and Version number.
For example:
./gscloud version
Version:        0.2.0-beta
Git commit:     66a9631ed5c1516d34ca305d4432149b67675cd0
https://gridscale.atlassian.net/browse/GD-2675
> Changed text for gscloud --help

- cmd/network.go
- cmd/server.go
- cmd/sshKey.go
- cmd/storage.go
- Easy add your keys via file and give it an alias/name
- To remove a key, all you need is it's ID or NAME
- Using logrus instead of panic now for sshKeyCmd, serverCmd, storageCmd and networkCmd
$ ./gscloud ssh-key
$ ./gscloud ssh-key --id
$ ./gscloud ssh-key add --name <name/alias> --file <path/to/file>
$ ./gscloud ssh-key remove --name <[alias]or[uuid]>
```
Fixes https://github.com/gridscale/gscloud/issues/30
> SSH-Key Management

- cmd/network.go
- cmd/root.go
- cmd/server.go
- cmd/sshKey.go
- cmd/storage.go
```
$ gscloud server --quiet
$ gscloud storage --quiet
$ gscloud network --quiet
$ gscloud ssh-key --quiet
```
Fixes https://github.com/gridscale/gscloud/issues/33
See also, refactor: rowsToDisplay -> upToColumn
> Quiet flag, prints ID column without heading

- CHANGELOG.md
- README.md
- cmd/network.go
- cmd/root.go
- cmd/server.go
- cmd/sshKey.go
- cmd/storage.go
- cmd/version.go
This PR contains following changes:
- Make sure that `ls` is always a sub-command of {server,storage,network,ssh-key}`.
- Clearly distinct between flag and argument
- Properly handle errors
- Always return non-zero exit code on error
- Also make sure that README and help texts are consistent and up-to-date
> Make ls a proper command

- README.md
- cmd/completion.go
- Add completion for bash and zsh
- Update README
Example:
```
$./gscloud server TAB TAB
ls   -- List server
off  -- Turn server off
on   -- Turn server on
```
Resolves https://github.com/gridscale/gscloud/pull/40
Fixes https://github.com/gridscale/gscloud/pull/46 GD-2683
> Tab-Completion

- cmd/makeConfig.go
Currently the output of ``gscloud --help make-config`` looks like this for me:
```
Create a new and possibly almost empty configuration file overwriting an
existing one if it exists. Prints the path to the newly created file to
stdout.
Examples:
Create a new configuration file at the default configuration path
(/Users/Wouter/Library/Application Support/gscloud/config.yaml/config.yaml):
gscloud make-config
Create a new configuration file at a specified path:
gscloud --config ~/myconfig.yaml make-config
Usage:
gscloud make-config [flags]
Global Flags:
--account string   Specify the account used; 'default' if none given
--config string    Specify a configuration file; default /Users/Wouter/Library/Application Support/gscloud/config.yaml
-h, --help             Print usage
-j, --json …
```
> Show correct config path in --help for make-config

- go.mod
- go.sum
- render/render.go
Hi there! I'm not a gridscale user, I'm mostly searching for needs-help and good-first-issues. I believe this should take care of issue #52 
Since I don't have an account, it's hard to verify 100% on my side, but I double-checked the versions and go.sum seemed to pull down the correct hashes.
> Updated dependency and ran go mod tidy

- cmd/kubernetes.go
- go.mod
- go.sum
This PR addresses #67.
First, it updates gsclient-go version to 3.2 to have `expiration_time` in `paas_service` credentials and second, it  changes fetchKubeConfigFromProvider signature to also return the expiration time.
To verify, check that
$ gscloud kubernetes cluster exec-credential --cluster=<ID>
saves the credential expiration time stamp from the PaaS definition in the cache directory.
> Use kubeconfig expire timestamp

- cmd/server.go
- cmd/server_test.go
- cmd/storage_test.go
- runtime/account_test.go
- runtime/runtime.go
Switches home-grown interfaces for those now in gsclient. Makes things actually not much less verbose, but hey, better type safe boilerplate than….
> Use operator interfaces from gsclient-go

- .github/workflows/release.yml
Changes:
- Add gpg signing in `release` GH workflow.
Required changes in repo's settings:
- Add RELEASE_SIGNING_KEY as a secret variable, and put string content of the gpg private key in it.
- Add RELEASE_SIGNING_KEY_PASSPHRASE as a secret variable, and put passphrase of the gpg private key in it.
> Sign release with gpg key

- cmd/server.go
- cmd/server_test.go
1. Add more unit tests and test cases for the existing tests of server cmd.
2. Use testify/mock to mock objects. This makes mocking a lot easier.
3. Move `...CmdRun` out of `cobra.Command`. So that the test coverage tool can detect these `...CmdRun` functions -> calculate the correct test cov.
> Add more unit tests for server commands

- cmd/info.go
- runtime/config.go
- runtime/runtime.go
Add a gscloud info that quickly gives you a rough overview of the current working account.
- token.
- user ID.
- API URL used.
- Object counts of servers, storages, IP addresses, and PaaS services.
> Add info command

- cmd/isoImage.go
- cmd/network.go
- cmd/server.go
These commands would print the UUID of the object they created, but not in JSON even when --json was given. Fixes #95
> Return valid json when --json is given

- cmd/root.go
If GSCLOUD_ACCOUNT is present, use its value instead of "default" when
no --account was given. --account has precedence over GSCLOUD_ACCOUNT,
allowing for a configuration with one default account and multiple
others in the config that aren't used often
Fixes #138
> Add env variable to control account (#138)

- cmd/manpage.go
Adds the requirement to specify exactly one argument when calling `gscloud manpage`
Fixes #150
> Fix manpage crash (#150)

- cmd/root.go
- cmd/root_test.go
- runtime/config.go
- runtime/runtime.go
- runtime/runtime_test.go
Uses rootCmd.Find(os.Args[1:]). Fixes #147
> Fix CommandWithoutConfig

- cmd/ip.go
- cmd/isoImage.go
- cmd/network.go
- cmd/root.go
- cmd/server.go
- cmd/storage.go
By adding shorthands for --name and --force where there were none before, and removing empty shorthands
> Increase consistency of flags

- cmd/info.go
The old implementation relied on the first wg.Add(1) to be called before
wg.Wait(), or else the channel could be closed before the tasks even
started. This probably never happened because calling go-routines is
slower than starting the loop, but if anything had been put inbetween,
this would've failed to load the data
> Only close channel after tasks have finished

- CHANGELOG.md
I tried to prevent merge conflicts with #153 while not including anything specific to that pull request. The `GRIDSCALE_ACCOUNT` / `GRIDSCALE_PROJECT` environment variable will be documented by #153
> Add changes to CHANGELOG.md

- cmd/info.go
- cmd/kubernetes.go
- runtime/runtime.go
- runtime/runtime_test.go
Before, accountName and config were saved, and to get the account you had to manually search for the right account in the config. Now the config and accountName are no longer saved in Runtime, because they're not used anywhere in the program, and instead the account is saved in Runtime
> Improve account handling in Runtime

- README.md
The documentation did not explain the effect of passing in `--credential-plugin`, it just assumed that it would be passed in as given in the example command.
Also add a remark for use of gscloud in the context of a pipeline.
> Further explain credential plugin support and use in pipelines
